// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Button': typeof import("../components/Button.vue")['default'],
    'Carusel': typeof import("../components/Carusel.vue")['default'],
    'CollectionItem': typeof import("../components/CollectionItem.vue")['default'],
    'Container': typeof import("../components/Container.vue")['default'],
    'Discover': typeof import("../components/Discover.vue")['default'],
    'Fact': typeof import("../components/Fact.vue")['default'],
    'Image': typeof import("../components/Image.vue")['default'],
    'InnerHeader': typeof import("../components/InnerHeader.vue")['default'],
    'InspirationItem': typeof import("../components/InspirationItem.vue")['default'],
    'ListIcon': typeof import("../components/ListIcon.vue")['default'],
    'Loading': typeof import("../components/Loading.vue")['default'],
    'Logo': typeof import("../components/Logo.vue")['default'],
    'NavButton': typeof import("../components/NavButton.vue")['default'],
    'NewsItem': typeof import("../components/NewsItem.vue")['default'],
    'Page': typeof import("../components/Page.vue")['default'],
    'PageNotFound': typeof import("../components/PageNotFound.vue")['default'],
    'ProductGrid': typeof import("../components/ProductGrid.vue")['default'],
    'ProductItem': typeof import("../components/ProductItem.vue")['default'],
    'Select': typeof import("../components/Select.vue")['default'],
    'Seo': typeof import("../components/Seo.vue")['default'],
    'Spinner': typeof import("../components/Spinner.vue")['default'],
    'State': typeof import("../components/State.vue")['default'],
    'TagContainer': typeof import("../components/TagContainer.vue")['default'],
    'Test': typeof import("../components/Test.vue")['default'],
    'Toggle': typeof import("../components/Toggle.vue")['default'],
    'ContactForm': typeof import("../components/contact/Form.vue")['default'],
    'ContactIntro': typeof import("../components/contact/Intro.vue")['default'],
    'CollectionPage': typeof import("../components/collection/CollectionPage.vue")['default'],
    'CollectionCollections': typeof import("../components/collection/Collections.vue")['default'],
    'ContentBanner': typeof import("../components/content/Banner.vue")['default'],
    'ContentBlocks': typeof import("../components/content/Blocks.vue")['default'],
    'Content': typeof import("../components/content/Content.vue")['default'],
    'ContentEmbed': typeof import("../components/content/Embed.vue")['default'],
    'ContentLatestContent': typeof import("../components/content/LatestContent.vue")['default'],
    'ContentMediaGrid': typeof import("../components/content/MediaGrid.vue")['default'],
    'ContentPosters': typeof import("../components/content/Posters.vue")['default'],
    'ContentSilhouettes': typeof import("../components/content/Silhouettes.vue")['default'],
    'ContentText': typeof import("../components/content/Text.vue")['default'],
    'FilterCheckBox': typeof import("../components/filter/CheckBox.vue")['default'],
    'Filter': typeof import("../components/filter/Filter.vue")['default'],
    'FilterButton': typeof import("../components/filter/FilterButton.vue")['default'],
    'FilterCheckBoxDress': typeof import("../components/filter/FilterCheckBoxDress.vue")['default'],
    'FilterItem': typeof import("../components/filter/FilterItem.vue")['default'],
    'FilterModal': typeof import("../components/filter/FilterModal.vue")['default'],
    'HeaderDropdown': typeof import("../components/header/Dropdown.vue")['default'],
    'Header': typeof import("../components/header/Header.vue")['default'],
    'HeaderSearchModal': typeof import("../components/header/SearchModal.vue")['default'],
    'HeaderWishCounter': typeof import("../components/header/WishCounter.vue")['default'],
    'Footer': typeof import("../components/footer/Footer.vue")['default'],
    'StickyBarBack': typeof import("../components/stickyBar/Back.vue")['default'],
    'StickyBarIcon': typeof import("../components/stickyBar/BarIcon.vue")['default'],
    'StickyHeader': typeof import("../components/stickyBar/StickyHeader.vue")['default'],
    'StickyMenu': typeof import("../components/stickyBar/StickyMenu.vue")['default'],
    'StoreFlag': typeof import("../components/store/Flag.vue")['default'],
    'StoreMap': typeof import("../components/store/Map.vue")['default'],
    'StoreItem': typeof import("../components/store/StoreItem.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyButton': typeof import("../components/Button.vue")['default'],
    'LazyCarusel': typeof import("../components/Carusel.vue")['default'],
    'LazyCollectionItem': typeof import("../components/CollectionItem.vue")['default'],
    'LazyContainer': typeof import("../components/Container.vue")['default'],
    'LazyDiscover': typeof import("../components/Discover.vue")['default'],
    'LazyFact': typeof import("../components/Fact.vue")['default'],
    'LazyImage': typeof import("../components/Image.vue")['default'],
    'LazyInnerHeader': typeof import("../components/InnerHeader.vue")['default'],
    'LazyInspirationItem': typeof import("../components/InspirationItem.vue")['default'],
    'LazyListIcon': typeof import("../components/ListIcon.vue")['default'],
    'LazyLoading': typeof import("../components/Loading.vue")['default'],
    'LazyLogo': typeof import("../components/Logo.vue")['default'],
    'LazyNavButton': typeof import("../components/NavButton.vue")['default'],
    'LazyNewsItem': typeof import("../components/NewsItem.vue")['default'],
    'LazyPage': typeof import("../components/Page.vue")['default'],
    'LazyPageNotFound': typeof import("../components/PageNotFound.vue")['default'],
    'LazyProductGrid': typeof import("../components/ProductGrid.vue")['default'],
    'LazyProductItem': typeof import("../components/ProductItem.vue")['default'],
    'LazySelect': typeof import("../components/Select.vue")['default'],
    'LazySeo': typeof import("../components/Seo.vue")['default'],
    'LazySpinner': typeof import("../components/Spinner.vue")['default'],
    'LazyState': typeof import("../components/State.vue")['default'],
    'LazyTagContainer': typeof import("../components/TagContainer.vue")['default'],
    'LazyTest': typeof import("../components/Test.vue")['default'],
    'LazyToggle': typeof import("../components/Toggle.vue")['default'],
    'LazyContactForm': typeof import("../components/contact/Form.vue")['default'],
    'LazyContactIntro': typeof import("../components/contact/Intro.vue")['default'],
    'LazyCollectionPage': typeof import("../components/collection/CollectionPage.vue")['default'],
    'LazyCollectionCollections': typeof import("../components/collection/Collections.vue")['default'],
    'LazyContentBanner': typeof import("../components/content/Banner.vue")['default'],
    'LazyContentBlocks': typeof import("../components/content/Blocks.vue")['default'],
    'LazyContent': typeof import("../components/content/Content.vue")['default'],
    'LazyContentEmbed': typeof import("../components/content/Embed.vue")['default'],
    'LazyContentLatestContent': typeof import("../components/content/LatestContent.vue")['default'],
    'LazyContentMediaGrid': typeof import("../components/content/MediaGrid.vue")['default'],
    'LazyContentPosters': typeof import("../components/content/Posters.vue")['default'],
    'LazyContentSilhouettes': typeof import("../components/content/Silhouettes.vue")['default'],
    'LazyContentText': typeof import("../components/content/Text.vue")['default'],
    'LazyFilterCheckBox': typeof import("../components/filter/CheckBox.vue")['default'],
    'LazyFilter': typeof import("../components/filter/Filter.vue")['default'],
    'LazyFilterButton': typeof import("../components/filter/FilterButton.vue")['default'],
    'LazyFilterCheckBoxDress': typeof import("../components/filter/FilterCheckBoxDress.vue")['default'],
    'LazyFilterItem': typeof import("../components/filter/FilterItem.vue")['default'],
    'LazyFilterModal': typeof import("../components/filter/FilterModal.vue")['default'],
    'LazyHeaderDropdown': typeof import("../components/header/Dropdown.vue")['default'],
    'LazyHeader': typeof import("../components/header/Header.vue")['default'],
    'LazyHeaderSearchModal': typeof import("../components/header/SearchModal.vue")['default'],
    'LazyHeaderWishCounter': typeof import("../components/header/WishCounter.vue")['default'],
    'LazyFooter': typeof import("../components/footer/Footer.vue")['default'],
    'LazyStickyBarBack': typeof import("../components/stickyBar/Back.vue")['default'],
    'LazyStickyBarIcon': typeof import("../components/stickyBar/BarIcon.vue")['default'],
    'LazyStickyHeader': typeof import("../components/stickyBar/StickyHeader.vue")['default'],
    'LazyStickyMenu': typeof import("../components/stickyBar/StickyMenu.vue")['default'],
    'LazyStoreFlag': typeof import("../components/store/Flag.vue")['default'],
    'LazyStoreMap': typeof import("../components/store/Map.vue")['default'],
    'LazyStoreItem': typeof import("../components/store/StoreItem.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  }
}
export const Button: typeof import("../components/Button.vue")['default']
export const Carusel: typeof import("../components/Carusel.vue")['default']
export const CollectionItem: typeof import("../components/CollectionItem.vue")['default']
export const Container: typeof import("../components/Container.vue")['default']
export const Discover: typeof import("../components/Discover.vue")['default']
export const Fact: typeof import("../components/Fact.vue")['default']
export const Image: typeof import("../components/Image.vue")['default']
export const InnerHeader: typeof import("../components/InnerHeader.vue")['default']
export const InspirationItem: typeof import("../components/InspirationItem.vue")['default']
export const ListIcon: typeof import("../components/ListIcon.vue")['default']
export const Loading: typeof import("../components/Loading.vue")['default']
export const Logo: typeof import("../components/Logo.vue")['default']
export const NavButton: typeof import("../components/NavButton.vue")['default']
export const NewsItem: typeof import("../components/NewsItem.vue")['default']
export const Page: typeof import("../components/Page.vue")['default']
export const PageNotFound: typeof import("../components/PageNotFound.vue")['default']
export const ProductGrid: typeof import("../components/ProductGrid.vue")['default']
export const ProductItem: typeof import("../components/ProductItem.vue")['default']
export const Select: typeof import("../components/Select.vue")['default']
export const Seo: typeof import("../components/Seo.vue")['default']
export const Spinner: typeof import("../components/Spinner.vue")['default']
export const State: typeof import("../components/State.vue")['default']
export const TagContainer: typeof import("../components/TagContainer.vue")['default']
export const Test: typeof import("../components/Test.vue")['default']
export const Toggle: typeof import("../components/Toggle.vue")['default']
export const ContactForm: typeof import("../components/contact/Form.vue")['default']
export const ContactIntro: typeof import("../components/contact/Intro.vue")['default']
export const CollectionPage: typeof import("../components/collection/CollectionPage.vue")['default']
export const CollectionCollections: typeof import("../components/collection/Collections.vue")['default']
export const ContentBanner: typeof import("../components/content/Banner.vue")['default']
export const ContentBlocks: typeof import("../components/content/Blocks.vue")['default']
export const Content: typeof import("../components/content/Content.vue")['default']
export const ContentEmbed: typeof import("../components/content/Embed.vue")['default']
export const ContentLatestContent: typeof import("../components/content/LatestContent.vue")['default']
export const ContentMediaGrid: typeof import("../components/content/MediaGrid.vue")['default']
export const ContentPosters: typeof import("../components/content/Posters.vue")['default']
export const ContentSilhouettes: typeof import("../components/content/Silhouettes.vue")['default']
export const ContentText: typeof import("../components/content/Text.vue")['default']
export const FilterCheckBox: typeof import("../components/filter/CheckBox.vue")['default']
export const Filter: typeof import("../components/filter/Filter.vue")['default']
export const FilterButton: typeof import("../components/filter/FilterButton.vue")['default']
export const FilterCheckBoxDress: typeof import("../components/filter/FilterCheckBoxDress.vue")['default']
export const FilterItem: typeof import("../components/filter/FilterItem.vue")['default']
export const FilterModal: typeof import("../components/filter/FilterModal.vue")['default']
export const HeaderDropdown: typeof import("../components/header/Dropdown.vue")['default']
export const Header: typeof import("../components/header/Header.vue")['default']
export const HeaderSearchModal: typeof import("../components/header/SearchModal.vue")['default']
export const HeaderWishCounter: typeof import("../components/header/WishCounter.vue")['default']
export const Footer: typeof import("../components/footer/Footer.vue")['default']
export const StickyBarBack: typeof import("../components/stickyBar/Back.vue")['default']
export const StickyBarIcon: typeof import("../components/stickyBar/BarIcon.vue")['default']
export const StickyHeader: typeof import("../components/stickyBar/StickyHeader.vue")['default']
export const StickyMenu: typeof import("../components/stickyBar/StickyMenu.vue")['default']
export const StoreFlag: typeof import("../components/store/Flag.vue")['default']
export const StoreMap: typeof import("../components/store/Map.vue")['default']
export const StoreItem: typeof import("../components/store/StoreItem.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyButton: typeof import("../components/Button.vue")['default']
export const LazyCarusel: typeof import("../components/Carusel.vue")['default']
export const LazyCollectionItem: typeof import("../components/CollectionItem.vue")['default']
export const LazyContainer: typeof import("../components/Container.vue")['default']
export const LazyDiscover: typeof import("../components/Discover.vue")['default']
export const LazyFact: typeof import("../components/Fact.vue")['default']
export const LazyImage: typeof import("../components/Image.vue")['default']
export const LazyInnerHeader: typeof import("../components/InnerHeader.vue")['default']
export const LazyInspirationItem: typeof import("../components/InspirationItem.vue")['default']
export const LazyListIcon: typeof import("../components/ListIcon.vue")['default']
export const LazyLoading: typeof import("../components/Loading.vue")['default']
export const LazyLogo: typeof import("../components/Logo.vue")['default']
export const LazyNavButton: typeof import("../components/NavButton.vue")['default']
export const LazyNewsItem: typeof import("../components/NewsItem.vue")['default']
export const LazyPage: typeof import("../components/Page.vue")['default']
export const LazyPageNotFound: typeof import("../components/PageNotFound.vue")['default']
export const LazyProductGrid: typeof import("../components/ProductGrid.vue")['default']
export const LazyProductItem: typeof import("../components/ProductItem.vue")['default']
export const LazySelect: typeof import("../components/Select.vue")['default']
export const LazySeo: typeof import("../components/Seo.vue")['default']
export const LazySpinner: typeof import("../components/Spinner.vue")['default']
export const LazyState: typeof import("../components/State.vue")['default']
export const LazyTagContainer: typeof import("../components/TagContainer.vue")['default']
export const LazyTest: typeof import("../components/Test.vue")['default']
export const LazyToggle: typeof import("../components/Toggle.vue")['default']
export const LazyContactForm: typeof import("../components/contact/Form.vue")['default']
export const LazyContactIntro: typeof import("../components/contact/Intro.vue")['default']
export const LazyCollectionPage: typeof import("../components/collection/CollectionPage.vue")['default']
export const LazyCollectionCollections: typeof import("../components/collection/Collections.vue")['default']
export const LazyContentBanner: typeof import("../components/content/Banner.vue")['default']
export const LazyContentBlocks: typeof import("../components/content/Blocks.vue")['default']
export const LazyContent: typeof import("../components/content/Content.vue")['default']
export const LazyContentEmbed: typeof import("../components/content/Embed.vue")['default']
export const LazyContentLatestContent: typeof import("../components/content/LatestContent.vue")['default']
export const LazyContentMediaGrid: typeof import("../components/content/MediaGrid.vue")['default']
export const LazyContentPosters: typeof import("../components/content/Posters.vue")['default']
export const LazyContentSilhouettes: typeof import("../components/content/Silhouettes.vue")['default']
export const LazyContentText: typeof import("../components/content/Text.vue")['default']
export const LazyFilterCheckBox: typeof import("../components/filter/CheckBox.vue")['default']
export const LazyFilter: typeof import("../components/filter/Filter.vue")['default']
export const LazyFilterButton: typeof import("../components/filter/FilterButton.vue")['default']
export const LazyFilterCheckBoxDress: typeof import("../components/filter/FilterCheckBoxDress.vue")['default']
export const LazyFilterItem: typeof import("../components/filter/FilterItem.vue")['default']
export const LazyFilterModal: typeof import("../components/filter/FilterModal.vue")['default']
export const LazyHeaderDropdown: typeof import("../components/header/Dropdown.vue")['default']
export const LazyHeader: typeof import("../components/header/Header.vue")['default']
export const LazyHeaderSearchModal: typeof import("../components/header/SearchModal.vue")['default']
export const LazyHeaderWishCounter: typeof import("../components/header/WishCounter.vue")['default']
export const LazyFooter: typeof import("../components/footer/Footer.vue")['default']
export const LazyStickyBarBack: typeof import("../components/stickyBar/Back.vue")['default']
export const LazyStickyBarIcon: typeof import("../components/stickyBar/BarIcon.vue")['default']
export const LazyStickyHeader: typeof import("../components/stickyBar/StickyHeader.vue")['default']
export const LazyStickyMenu: typeof import("../components/stickyBar/StickyMenu.vue")['default']
export const LazyStoreFlag: typeof import("../components/store/Flag.vue")['default']
export const LazyStoreMap: typeof import("../components/store/Map.vue")['default']
export const LazyStoreItem: typeof import("../components/store/StoreItem.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const componentNames: string[]
